name: DBH
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Git pull
      run: |
        cd
        git init
        git pull https://github.com/Kyro3400/dbh-api-docs.git
        npm i
